server:
  port: 8082

spring:
  application:
    name: Cards
  datasource:
    username: 'pguser'
    password: 'pgpassword'
    url: jdbc:postgresql://localhost:5432/cards_microservice
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: 'true'
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: ${spring.application.name:},%X{traceId:-},%X{spanId:-}

api:
  documentation:
    cardsMicroserviceUrl: http://localhost:8081/