server:
  port: 8083

spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
        - id: Cards
          uri: lb://CARDS
          predicates:
            - Path=/api/v1/cards/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
