server:
  port: 8083

spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
        - id: Cards
          uri: lb://CARDS
          predicates:
            - Path=/api/v1/cards/**
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0
